services:
  kavita:
    restart: unless-stopped
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/config
      - ./data:/data #optional
    ports:
      - 8037:5000
    networks:
      - server-net

networks:
  server-net:
    external: true
