networks:
  server-net:
    external: true

volumes:
  open-webui:


services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      # OpenAI
      - ENABLE_OPENAI_API=true
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL:-https://openrouter.ai/api/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # Recomendado: definir uma chave real
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      # Opcional (útil se você quer que as env vars continuem valendo após restart)
      # - ENABLE_PERSISTENT_CONFIG=false
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
